version: '3'

services:

  postgres:
    image: postgres:latest
    ports:
      - "5400:5432"
    environment:
      POSTGRES_DB: card-service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
        - postgres-db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8095:8095"
    volumes:
      - card_service_db_data:/var/lib/postgres
      - card_service_db_config:/etc/postgres/conf.d
    depends_on:
      - postgres
    networks:
      - postgres-db

volumes:
  card_service_db_data:
  card_service_db_config:

networks:
  postgres-db:
    driver: bridge