version: '3'

services:

  postgres:
    image: postgres:latest
    ports:
      - "5400:5432"
    environment:
      POSTGRES_DB: card-service
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    networks:
        - postgres-db

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8095:8095"
    volumes:
      - card-service-db-data:/var/lib/postgresql/data
    depends_on:
      - postgres
    networks:
      - postgres-db

volumes:
  card-service-db-data:

networks:
  postgres-db:
    driver: bridge