server:
  port: 0

spring:
  application:
    name: memorizing-core

  cloud:
    inetutils:
      preferred-networks: true

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
